### ISSUE TITLE
There is already a java library named easywechat, package name started with "org.easywechat"

### ISSUE THREAD

**Issue by SubiRUN** [lvxiang/EasyWechat#1]
I authored [a project named easywechat](https://github.com/outstudio/easywechat) about 2 months ago. The package name starts with  "org.easywechat". I think maybe one of us should change the package name. We can talk about this. And I notice your copyright belongs to Alibaba.com, so I want to say, I will daxuebiye in 2016, qiu nei tui!

**Comment by lvxiang** [comment]
你好， 我就讲中文了，这个库是我最近项目中写的，很新，也没什么影响力，你需要的话我就改成simplewechat之类的好了。 16年毕业现在内推有点早啊，明年春招来实习倒是不错，现在内推渠道都关闭了。 幸会 lv------------------ 原始邮件 ------------------
发件人: "SubiRUN"notifications@github.com
发送时间: 2014年10月8日(星期三) 晚上8:22
收件人: "lvxiang/EasyWechat"EasyWechat@noreply.github.com;
主题: [EasyWechat] There is already a java library named easywechat,package name started with "org.easywechat" (#1)

I authored a project named easywechat about 2 months ago. The package name starts with  "org.easywechat". I think maybe one of us should change the package name. We can talk about this. And I notice your copyright belongs to Alibaba.com, so I want to say, I will daxuebiye in 2016, qiu nei tui! 

&mdash;
